### ISSUE TITLE
Anti-Cheese Implementation

### ISSUE THREAD

**Issue by Caltinor** [Caltinor/Project-MMO-2.0#189]
# Anti-Cheese
This system handles various abuse cases where players use exploitive play aspects to advance in unintended ways.  Examples include AFK farming of XP such as combining an infinite damage source with an infinite healing source to gain xp connected with both events.  

The problem with this feature, to-date, has been it's inability to give enough control to server owners over the anti-cheese features.  Prior implementations did give some customizability, such as excluding certain skills from the AFK reduction.  The implementation proposed in this issue aims to drastically expand the customization options with the intent of making Anti-Cheese the powerful tool it was meant to be.

## Features To Implement
- [x] Granular Customization
- [x] AFK Tracking
- [x] Diminishing XP
- [x] XP Normalization

### Granular Customization
Customization in this implementation will allow control of when features are applied starting at the event level and drilling down to the skills and even object contexts.  This intent with this granularity is to allow operators to apply anti-cheese as specifically as possible so that the behavior only applies to features that need them.  For example spell books from certain magic mods can be spammed for XP.  these would benefit from diminished xp, but could be configured to only affect those items so something like a shovel paving paths is not affected in the same way.

### AFK Tracking
This feature keeps track of how long players are AFK and applies xp modification based on properties of their AFK status.  For example this prevents passive swimming xp from going afk under water with a conduit.

### Diminishing XP
This feature causes XP to be reduced under certain conditions, such as repeatedly earning the same XP from riding animals for example.

### XP Normalization
This feature makes it so spikes in XP are reduced to a threshold relative to the last xp amount earned.  This makes certain xp cases ramping instead of instantly massive.  One cheese this addresses is sprint xp from free falling while holding sprint key.

## Configuration Design
As stated above, granularity is the objective.  Depending on the Anti-Cheese feature being implemented, customization options will vary.  The following is a pseudo-example of what the config might look like 
```toml
[Anti-Cheese]
  [Anti-Cheese.AFK]
    [[Anti-Cheese.AFK.FROM_ENVIRONMENT]]
      #specified sources.  if omitted, all sources are applicable
      source= ["minecraft:campfire", "minecraft:soul_campfire"]
      #how many ticks before a player is considered to be accruing AFK duration
      min_time_to_apply = 30000
      #how much reduction do they accrue per AFK duration accrued
      reduction_per_tick = 0.05
      #once they are active again, how quickly does their AFK duration reduce
      #Note: this is a per-activity afk duration, not a global duration.  Therefore it is 
      #possible to have certain activities suffer more from AFK than others.
      cooloff_per_tick = 0.01
  [Anti-Cheese.DiminishingXP]
    [[Anti-Cheese.DiminishingXP.RIDING]]
      source=["minecraft:horse","minecraft:boat"]
      #how much to reduce xp by per repeated proc
      reduction_per_occurance=0.10
      #how long to retain the last value before resetting repeat count
      cooloff_duration=30000
  [Anti-Cheese.Normalization]
    [[Anti-Cheese.Normalization.SPRINTING]]
      #what percent of the previous xp value above the last value is normal
      tolerance_percent=0.3
      #what amount above the previous xp vlaue is normal (mutually exclusive to percent tolerance)
      tolerance_flat=10
      #how long to retain the current tolerance values before starting over
      retention_duration=3000
```
