### ISSUE TITLE
[Feature Request] [1.20] Multiplicative Numerical Perk Bonuses

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#242]
**Describe the solution you'd like**
Currently, all numerical perks are applied in an additive manner. 

I propose that a way to apply scaling numerical values be implemented.

Ex:

```TOML
[[Perks.For_Event.RANGED_TO_MOBS.archery]]
    applies_to = ["minecraft:bow", "mineraft:crossbow", "minecraft:trident"]
    perk = "pmmo:damage_boost"
    per_level = 0.01
    base = 1.0
    multiplicative = true
```
So at level 10 `Archery` it would be a 1.1x multiplier to the damage of bows, crossbows, and tridants.

**Why is this feature needed**
A way to make Perk bonuses so that they don't make the initial value less important than the bonus being applied.
