### ISSUE TITLE
Vein Mining Stats For Player Entities

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#306]
**Describe the solution you'd like**
Being able to set vein data for the player entity and have it add to item-sourced data.

```JSON
  "vein_data": {
    "chargeCap": 0,
    "chargeRate": 0.0
  }
```

**Why is this feature needed**
To allow a background regen/cap to be set.

**Describe alternatives you've considered**
Having it as an option in the `pmmo-server.toml` file.

**Comment by Caltinor** [comment]
Having it as an option in the server toml is the better approach.  
```toml
[Vein Settings]
#how much vein players gain passively.  is additive with items
passive_charge_rate = 0.01
#the vein cap players maintain when no items are involved
passive_vein_cap = 5
```
This is easier than the datapack part.
