### ISSUE TITLE
Mob Scaling Settings Config Generation

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#341]
**Describe the bug**
When `pmmo-server.toml` is created, the settings for mob scaling ratios is set up badly.

This code:

https://github.com/Caltinor/Project-MMO-2.0/blob/main/src/main/java/harmonised/pmmo/config/Config.java#L501-#L506

Produces the following:
```TOML
	[Mob_Scaling.Scaling_Settings]

		[Mob_Scaling.Scaling_Settings."Mob Scaling IDs and Ratios"]

			[Mob_Scaling.Scaling_Settings."Mob Scaling IDs and Ratios"."minecraft:generic"]

				[Mob_Scaling.Scaling_Settings."Mob Scaling IDs and Ratios"."minecraft:generic".max_health]
					combat = 0.01

				[Mob_Scaling.Scaling_Settings."Mob Scaling IDs and Ratios"."minecraft:generic".attack_damage]
					combat = 0.001

				[Mob_Scaling.Scaling_Settings."Mob Scaling IDs and Ratios"."minecraft:generic".movement_speed]
					combat = 1.0E-5
```

Note the `."minecraft:generic"` in the 3rd key down and the `."minecraft:generic".attack_damage` and the like in the deeper keys.

**Expected behavior**
It should produce this, I believe:
```TOML
	[Mob_Scaling.Scaling_Settings]

		[Mob_Scaling.Scaling_Settings."Mob Scaling IDs and Ratios"]

			[Mob_Scaling.Scaling_Settings."Mob Scaling IDs and Ratios"."minecraft:generic.max_health"]
				combat = 0.01

			[Mob_Scaling.Scaling_Settings."Mob Scaling IDs and Ratios"."minecraft:generic.attack_damage"]
				combat = 0.001

			[Mob_Scaling.Scaling_Settings."Mob Scaling IDs and Ratios"."minecraft:generic.movement_speed"]
				combat = 1.0E-5
```

**To Reproduce**
1. Try to edit any of the default values, even to `0.0`
2. They do nothing because it isn't reading them
3. Cry in a corner as a warp-zombie pwns you

**Versions:**
All rework version

**Additional context**
Pattern analysis.
