### ISSUE TITLE
Perks Event Skill Filter

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#411]
**Describe the solution you'd like**
Two ideas for the `skill` entry in perks:

`#all` would make the perk trigger for any skill going up. This would have the immediate use with `pmmo:fireworks` perks and would consolidate them all down to one perk entry.

`["combat", "endurance"]` allowing the `skill` field to take an array so it would apply for any of the listed skills. This would mean certain perks could have multiple skills that trigger them. ex: 

```TOML
		[[Perks.For_Event.SPRINT_JUMP]]
			skill = ["agility", "combat"]
			per_level = 0.001
			perk = "pmmo:jump_boost"
```

**Why is this feature needed**
`pmmo-Perks.toml` is a bit messy, and adding either an "#all" keyword or allowing it to take a list of skills would get rid of a lot of that. Also, it would allow for multiple skills to trigger the same perk.

**Describe alternatives you've considered**
Status Quo.

**Additional context**
Just a lazy Sunday afternoon's musing.
