### ISSUE TITLE
`pmmo:damage_reduce` Perk Not Accepting Tag Groups

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#419]
**Describe the bug**
I tried making a damage tag called `#pmmo:all` (by including a list of all Minecraft damage types). Adding that to the `for_damage` line of a `pmmo:damage_reduce` perk (with or without a # in it) doesn't trigger the perk.

```TOML
		[[Perks.For_Event.RECEIVE_DAMAGE]]
			for_damage = "#pmmo:all"
			skill = "archery"
			per_level = 0.025
			perk = "pmmo:damage_reduce"
```

**Expected behavior**
With high enough skill in `archery`, I should take no fall damage from small falls.

**To Reproduce**
Steps to reproduce the behavior: (easier by using one of PMMO's own damage groupings)
1. Make the following perk:
```TOML
		[[Perks.For_Event.RECEIVE_DAMAGE]]
			for_damage = "#pmmo:from_impact"
			skill = "archery"
			per_level = 0.025
			perk = "pmmo:damage_reduce"
```
2. Set `archery` to 300
3. Go creative, gain some height, then go to survival

**Screenshots**
```
[12Nov2023 20:53:45.852] [Server thread/DEBUG] [harmonised.pmmo.util.MsLoggy/]: Source Type: minecraft:fall | Source Raw: fall
[12Nov2023 20:53:45.852] [Server thread/DEBUG] [harmonised.pmmo.util.MsLoggy/]: Perk Executed: pmmo:damage_reduce
[12Nov2023 20:53:45.852] [Server thread/DEBUG] [harmonised.pmmo.util.MsLoggy/]: Damage Modified from 6.0 to 6.0
[12Nov2023 20:53:45.853] [Server thread/DEBUG] [harmonised.pmmo.util.MsLoggy/]: Merged Map: {endurance:15}
```

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.2.4
 - PMMO: 1.20.1-1.2.9

**Additional context**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/34b75147-fa99-48fd-9979-7c3de9ef595c
