### ISSUE TITLE
Anti-Cheese Option To Require Movement

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#480]
**Describe the solution you'd like**
A way to limit XP gain until someone has moved a specific distance from the last point they gained such XP.
```TOML
[AntiCheese.Movement]
    [AntiCheese.Movement.RIDING]
        moved_distance = 5
```
Basically, this would mean you cannot get `RIDING` xp until you have moved at least 5 blocks distance from the last point you were awarded `RIDING` xp.

**Why is this feature needed**
Force people to move to get certain xp types—`RIDING` being the big one. Could also be used to encourage moving around while mining.

**Describe alternatives you've considered**
Nothing. Not a thing. Just sedentary existence. Return to coral.

**Additional context**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/97296552-902a-444c-b1f6-f2a309d072e3
