### ISSUE TITLE
`pmmo:attribute` Perk Not Respecting Attribute Caps

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#496]
**Describe the bug**
Making a perk that tries to raise an attribute higher than the maximum allowed causes an error (it should probably be more explicit about why it is failing).

`[22:55:43] [Render thread/INFO] [minecraft/ChatComponent]: [System] [CHAT] An unexpected error occurred trying to execute that command`

**Expected behavior**
Either notifying the user that the perk is badly configured or silently giving the max allowed.

**To Reproduce**
1. Make a perk like:
```TOML
        [[Perks.For_Event.SKILL_UP]]
            perk = "pmmo:attribute"
            skill = "endurance"
            attribute = "minecraft:generic.armor"
            per_level = 1
            max_boost = 40
```
2. Try to give yourself 40 levels in `endurance`
3. See error

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.1.3
 - PMMO: 1.20.1-1.2.19

**Additional context**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/242701c1-f951-4295-831f-8c3bd3c1ec07
