### ISSUE TITLE
Huge xp earn

### ISSUE THREAD

**Issue by JasonFortis** [Caltinor/Project-MMO-2.0#565]
For example by running i'm getting 75 agility per second, or by mining dirt 187 excavation xp, is it supposed to be this way?

**Comment by Caltinor** [comment]
Yes,  this is normal.  You can change it if you like, but this is the default settings.

**Comment by JasonFortis** [comment]
thank you, how can i change it?

**Comment by SomewhatDamaged** [comment]
`minecraft/saves/<save name>/serverconfig/pmmo-server.toml`

Edit the following to a lower value. Do so with the game closed and with any editor except Notepad++.

```TOML
            [XP_Gains.Event_XP_Specifics.Player_Actions."SPRINTING Skills and Ratios"]
                agility = 100.0
```
