### ISSUE TITLE
PRs To Add Magic Damage

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#570]
Made PRs for 1.21 and 1.20.1 to add `#pmmo:magic` damage type to `damage_dealt` events.

Also adds Iron's Spellbooks damage types to `#pmmo:magic` tag.

- [1.20.1] https://github.com/Caltinor/Project-MMO-2.0/pull/568
- [1.21] https://github.com/Caltinor/Project-MMO-2.0/pull/569

A note: I followed the existing layouts for the java file, but I don't have a dev environment and haven't tested those. Please double-check them if you can.

**Comment by SomewhatDamaged** [comment]
One thing it is lacking is how to boost damage/mana with it.

Is there a way to make a perk like this apply to all of one damage type? Or can `applies_to` do that?
```TOML
		[[Perks.For_Event.DEAL_DAMAGE]]
			applies_to = ["ars_nouveau:spell_bow"]
			skill = "magic"
			perk = "pmmo:damage_boost"
```
