### ISSUE TITLE
Allow Damage Type Filtering for `pmmo:damage_boost` Perk

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#627]
**Describe the solution you'd like**
An alternative to limiting what weapons the perk affects being what damage types it affects. 

Eg:

```TOML
		[[Perks.For_Event.DEAL_DAMAGE]]
			damage_types = ["minecraft:arrow"]
			skill = "archery"
			perk = "pmmo:damage_boost"
```

**Why is this feature needed**
It would make sense with the focus on using damage types for combat events, as well as allow for far more ready 

**Describe alternatives you've considered**
Sleeping. Maybe for a year. 

**Additional context**

https://github.com/user-attachments/assets/48f4a6d4-4efa-41de-8cfa-9a62a1ca85ae
