### ISSUE TITLE
[1.20.1] `"namespace:*"` Matching All in `pmmo:damage_boost` Perk

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#660]
**Describe the bug**
It doesn't matter what namespace is used in a `damage_boost` perk, if it ends in `:*`, it will match ALL attacks (from any namespace).

**Expected behavior**
Should only match weapons from the specified namespace.

**To Reproduce**
Ex: 

```TOML
        [[Perks.For_Event.DEAL_DAMAGE]]
            applies_to = ["blargelumps:*"]
            skill = "upgoing"
            multiplicative = false
            base = 1000
            perk = "pmmo:damage_boost"
```
Results in:
```
[07Mar2025 13:53:48.541] [Server thread/INFO] [harmonised.pmmo.util.MsLoggy/]: Attack Type: DEAL_DAMAGE | TargetType: entity.dummmmmmy.target_dummy
[07Mar2025 13:53:48.549] [Server thread/DEBUG] [harmonised.pmmo.util.MsLoggy/]: Source Type: minecraft:player_attack | Source Raw: player
[07Mar2025 13:53:48.552] [Server thread/DEBUG] [harmonised.pmmo.util.MsLoggy/]: Pre-Perk Damage:1.0
[07Mar2025 13:53:48.553] [Server thread/DEBUG] [harmonised.pmmo.util.MsLoggy/]: Damage Modified from 1.0 to 1001.0
[07Mar2025 13:53:48.553] [Server thread/DEBUG] [harmonised.pmmo.util.MsLoggy/]: Attack Type: minecraft:player_attack | Damage Out: 1001.0
```

1. Remove all perks, add the example.
2. Add debug to see damage modifications
3. Hit something

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.3.22
 - PMMO: 1.20.1-1.6.33
### this will likely affect 1.21.1, since it uses the same code.

**Additional context**
Turn your sound up!

https://github.com/user-attachments/assets/73392dc5-608d-475b-a46f-bb0c507c248d
